export {Error404} from './Error/Error404'
export {MainPage} from 'pages/Main.page'
export {Adidas} from './Adidas/Adidas'
export {Puma} from './Puma/Puma'
export {Abibas} from './Abibas/Abibas'
export {Prices} from './Prices/Prices'
export {Secret} from './Secret/Secret'
export {Model} from './Model/Model'